coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
      target: 70%
    patch: true
    changes: false

comment:
  layout: "header, diff"
  behavior: default  # update if exists else create new
