export const EXAMPLE_DATA_REQUEST = 'app/DemoHome/EXAMPLE_DATA_REQUEST';
export const EXAMPLE_DATA_SUCCESS = 'app/DemoHome/EXAMPLE_DATA_SUCCESS';
export const EXAMPLE_DATA_FAILURE = 'app/DemoHome/EXAMPLE_DATA_FAILURE';
