export const EXAMPLE_DATA_REQUEST = 'app/Sagas/EXAMPLE_DATA_REQUEST';
export const EXAMPLE_DATA_SUCCESS = 'app/Sagas/EXAMPLE_DATA_SUCCESS';
export const EXAMPLE_DATA_FAILURE = 'app/Sagas/EXAMPLE_DATA_FAILURE';

export const CLEAR_ERRORS = 'app/Sagas/CLEAR_ERRORS';
